### ISSUE TITLE
Detecting by parameter names seems fragile

### ISSUE THREAD

**Issue by gaearon** [erikras/react-lazy-cache#1]
Wouldn't optimizations like crunching parameter names break this?
I think Uglify does this by default..

**Comment by erikras** [comment]
Good line of questioning. It definitely feels a little too angular-y.

The alternative is a `{ props: [ 'a', 'b', 'c' ], fn: (a, b, c) => {} }` structure, which is so much less aesthetic.

**Comment by erikras** [comment]
I suspect that you are right. Playing with js functions at runtime is probably too fragile.
